### ISSUE TITLE
Upgrade to SS4

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-superglue#1]
Hey Chris, long time no chat. Hope you're well!

I'm investigating an upgrade of this module to SS4 and PHP7 as part of upgrading a site that it's included on. I just wanted to check to see if you had any thoughts about the upgrade - whether you had been thinking about making any significant API changes or similar? If not, would you be happy if we worked on an upgrade and sent it through as a pull request? Ideally we'll be able to add some tests while we're at it :)

It would be awesome to consider how this could be applied to both pages (current) and also content blocks - not necessarily for this upgrade but at some point.

Thanks!

**Comment by ChloeSartorelli** [comment]
This module was made SS4 compatible in #2 - adding tests would still be good, but that should probably be raised as a separate issue (or this one renamed to reflect the part that's still relevant).

**Comment by satrun77** [comment]
Close ticket as it is Silverstripe 4 and 5 compatible
