### ISSUE TITLE
Move module to archive

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-superglue#3]
As this isn't a commercially supported module by SilverStripe Ltd, it perhaps should live in another namespace instead, e.g. silverstripe-archive, or be adopted by another maintainer.

cc @chillu @micmania1

**Comment by micmania1** [comment]
`silverstripeltd` namespace would be good as we still use/maintain this in our bespoke teams.

**Comment by robbieaverill** [comment]
Happy to transfer once @chillu gives the all clear

**Comment by chillu** [comment]
Yep, happy with that. Unless there's a maintainer, I'd move it to `silverstripe-archive`. It's a bit of an outdated concept now that we're pushing content blocks anyway

**Comment by robbieaverill** [comment]
Let's leave it where it is for now
